### ISSUE TITLE
Automated tests?

### ISSUE THREAD

**Issue by nk9** [nefrob/vscode-just#14]
It's great to see the work you've put into this syntax! Good job, thanks for doing this.

Have you considered porting (some of) the [syntax tests from the just_sublime repo](https://github.com/nk9/just_sublime/tree/main/Syntax/tests) to run against this version of the syntax? I don't believe the tests will actually run in VSCode, but they should run in Sublime, and they will give you a much more comprehensive way to get a sense of what works and what doesn't in the existing syntax. You can learn more about how to run the tests in the [CONTRIBUTING file](https://github.com/nk9/just_sublime/blob/main/CONTRIBUTING.md) in that repo.

**Comment by nefrob** [comment]
@nk9 that would be a good idea. It looks like this repo might support something similar to what you're suggesting: https://github.com/PanAeon/vscode-tmgrammar-test. I'll take a look at this when I have time.

**Comment by nefrob** [comment]
@nk9 here is a v1 to get something up quickly: https://github.com/nefrob/vscode-just/pull/16. I'll follow up in the coming weeks by splitting out the tests and correcting any issues.

**Comment by nk9** [comment]
Great work! Thanks for keeping us posted.

**Comment by nefrob** [comment]
Closing re https://github.com/nefrob/vscode-just/pull/20.
