### ISSUE TITLE
GitHub Linguist?

### ISSUE THREAD

**Issue by nk9** [nefrob/vscode-just#15]
Would you be interested in getting the syntax into a state that was sufficiently improved that it could be nominated for inclusion in GitHub Linguist? The current syntax [has issues](https://github.com/casey/just/issues/1626), and the work here would be in the same format, and thus potentially useable by Linguist. (Unfortunately, Linguist doesn't support the newst Sublime syntax, nor TreeSitter.)

**Comment by nefrob** [comment]
Ah hadn't heard of that before. If I have time to nail down the grammar accurately (currently just through things together pretty ad hoc) and gracefully handle the edge cases that require an LSP/parser to support that sounds like an option. Also open to contributions if you/anyone are/is particularly familiar with building syntax grammars.

**Comment by tgross35** [comment]
I spent a _lot_ of effort getting tree-sitter-just working well and pretty thoroughly tested, I don’t know how similar the patterns are but maybe it could serve as a reference: https://github.com/IndianBoy42/tree-sitter-just

**Comment by nefrob** [comment]
PR opened here: https://github.com/github-linguist/linguist/pull/6985.

**Comment by nefrob** [comment]
Now live: https://github.com/github-linguist/linguist/releases/tag/v8.0.0.
