### ISSUE TITLE
Single-quotes break formatting

### ISSUE THREAD

**Issue by macintacos** [nefrob/vscode-just#29]
Hello! Just started using this plugin, thanks for your work here.

The parser seems to break when you provide a single quote with no "closing" single-quote. I put "closing" in quotes because, in the context I was trying to use it (writing a comment) a "closing" quote doesn't make sense.

A screenshot is better to show you what's going on:

![CleanShot 2024-08-26 at 14 44 41@2x](https://github.com/user-attachments/assets/e5217937-9d33-44eb-bfab-3d06a6ebb9dc)

```justfile
test:
    @echo "This is a valid justfile"

    # This is a comment with a quote because it's a part of a contraction
    @echo "Everything after this shows green text like a string, until I put another single-quote character."

    @echo "I will go ahead and do it here ' even though it doesn't really matter uh oh"
    @echo There is it again!'

    @echo Okay it is gone now.
```

It seems like GitHub also struggles rendering this (I reported something similar in the `just` repo a while ago here: https://github.com/casey/just/issues/1626)

**Comment by nefrob** [comment]
Quotes in comments definitely shouldn't break like shown above. Solving for single quotes within strings might not be possible in textmate grammars but worth investigating. I would think escaping the character would work as intended, ex. `@echo "single \' quote"`.

**Comment by nefrob** [comment]
@macintacos this should be resolved. See the above code block in your comment now highlights as expected.
